[workspace]
members = ["gzset", "xtask"]

[workspace.package]
edition = "2021"
license = "MIT"

[workspace.dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
portpicker = "0.1"

[alias]
valkey = "run -p xtask -- start-valkey"
