name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    - name: Install Valkey
      run: sudo apt-get update && sudo apt-get install -y valkey-server valkey-tools
    - name: Build
      run: cargo build --all-targets --verbose
    - name: Format
      run: cargo fmt -- --check
    - name: Lint
      run: cargo clippy --all-targets -- -D warnings
    - name: Test
      run: cargo test --verbose
