name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install Valkey
        run: sudo apt-get update && sudo apt-get install -y valkey-server valkey-tools
        shell: bash
      - name: Format
        run: cargo fmt -- --check
        shell: bash
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
        shell: bash
      - name: Check duplicates
        run: cargo tree -d
        shell: bash
      - name: Test
        run: cargo test --all --all-targets --verbose
        shell: bash
