name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install Valkey (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y valkey-server valkey-tools
      - name: Install Valkey (Windows)
        if: runner.os == 'Windows'
        run: choco install valkey -y
      - name: Test
        run: cargo test --all --all-targets
